name: Lint and Test Chart

on:
  pull_request:
    paths:
      - "charts/external-dns/**"

jobs:
  lint-test:
    if: github.repository == 'kubernetes-sigs/external-dns'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v4.0.0
        with:
          fetch-depth: 0

      - name: Run Artifact Hub lint
        run: |
          set -euo pipefail
          curl -Lo ah_linux_amd64.tar.gz https://github.com/artifacthub/hub/releases/download/v1.9.0/ah_1.9.0_linux_amd64.tar.gz
          tar -xzvf ah_linux_amd64.tar.gz ah
          ./ah lint --kind helm || exit 1
          rm -f ./ah ./ah_linux_amd64.tar.gz

      - name: Set-up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Set-up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          python-version: "3.x"

      - name: Set-up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --check-version-increment=false

      - name: Set-up Kind cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
        with:
          wait: 120s
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install
